---

- name: Setup containerd, runc, and CNI
  hosts: localhost
  connection: local
  become: true

  vars:
    containerd_version: "2.2.1"
    containerd_arch: "amd64"
    containerd_os: "linux"
    runc_arch: "amd64"
    cni_version: "1.9.0"
    cni_arch: "amd64"
    cni_os: "linux"

  tasks:

    - name: Download containerd tarball
      ansible.builtin.get_url:
        url: "https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-{{ containerd_os }}-{{ containerd_arch }}.tar.gz"
        dest: "/tmp/containerd-{{ containerd_version }}.tar.gz"
        checksum: "sha256:https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-{{ containerd_os }}-{{ containerd_arch }}.tar.gz.sha256sum"
        mode: '0644'

    - name: Extract containerd tarball
      ansible.builtin.unarchive:
        src: "/tmp/containerd-{{ containerd_version }}.tar.gz"
        dest: "/usr/local"
        remote_src: yes
        creates: "usr/local/bin/containerd"

    - name: Create systemd directory for containerd
      ansible.builtin.file:
        path: /usr/local/lib/systemd/system
        state: directory
        mode: '0755'

    - name: Download containerd systemd service file
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/containerd/containerd/main/containerd.service"
        dest: "/usr/local/lib/systemd/system/containerd.service"
        mode: '0644'

    - name: Reload systemd daemon
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Enable and start containerd service
      ansible.builtin.systemd_service:
        name: containerd
        enabled: true
        state: started