---
name: YAML-Lint

on:
  push:
    branches: [main]
    paths:
      - '**/*.yml'
      - '**/*.yaml'

jobs:
  yaml-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install yamllint
        run: |
          pip install yamllint

      - name: Run YAML Lint
        run: |
          yamllint .
